---
title: "Making the most of useR!"
author: Laure Cougnaud, OpenAnalytics
date: 03 July 2017
output: 
  ioslides_presentation:
    self_contained: true
    css: custom.css
---

```{r, echo = FALSE}
	options(width = 150)
	library(knitr)
	knitr::opts_chunk$set(eval = TRUE, echo = FALSE)
	library(exampleReportingPackage)
```

## UseR! conference

* ~ 900 participants
* 16 tutorials, 112 talks, 6 concurrent lightning talk session
  (~10 talks/session)


## Organization (1)

* website: https://user2017.brussels
* useR!2017 app: [iOS App
  store](https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1246681655&mt=8)
  or [Google Play
  Store](https://play.google.com/store/apps/details?id=org.sched.user2017)
* possibility to provide picture

## Organization (2)

* plan session attendance in advance (cf app, wifi?)
* tutorials: check presenter guidelines
* multiple concurrent sessions:
     + can leave/change session (discreetly)
* ask for help: conference organizers
* 'clear your schedule'     
     
## Meeting opportunity

* dare to approach people/speakers during conference
     + ask questions during/after presentations, during breaks...
     + poster session: less informal
     + social networks: 
         + [twitter: #useR2017](https://twitter.com/UseR_Brussels)
         + facebook
* stay out of your confort zone
     
## Take it back home

* take notes: presenter, topic(s), new ideas/packages     
* slides, videos?

## In practice

* dress confortably

## Bonus

* Extra time for tourism: 
     + Belgium: cities, specialities
     + Brussels, 'center' of Europe

## Conclusions

* Enjoy the UseR! 2017 conference!

